export default 
{
    "datas":[
        {
            "texture":"../../textures/lensflare2.png",
            "size":300,
            "distance":0,
            "color":"0xFF00FD"
        },
        {
            "texture":"../../textures/lensflare0_alpha.png",
            "size":120,
            "distance":0,
            "color":"0x00FF16"
        },
        {
            "texture":"../../textures/lensflare3.png",
            "size":25,
            "distance":0.06,
            "color":"0xFF0000"
        },
        {
            "texture":"../../textures/lensflare3.png",
            "size":30,
            "distance":0.1,
            "color":"0x0026FF"
        },
        {
            "texture":"../../textures/lensflare3.png",
            "size":50,
            "distance":0.2,
            "color":"0x00F2FF"
        },
        {
            "texture":"../../textures/lensflare3.png",
            "size":25,
            "distance":0.3,
            "color":"0xFFFE00"
        }
    ]
}