export default 
{
    "position":{
        "x":0,
        "y":0,
        "z":0
    },
    "rotation":{
        "x":0,
        "y":0,
        "z":0,
        "w":1
    },
    "texturePath":"31b542f8fe2a4c8498cb7fdd80a32883",
    "offsetInitX":0,
    "offsetInitY":0,
    "tilingX":5,
    "tilingY":1,
    "tilingMoreX":2,
    "tilingMoreY":1,
    "offsetX":-0.01,
    "offsetY":0.01,
    "width":50,
    "useWorldSpace":true,
    "loop":true,
    "closed":false,
    "numCornerVertices":0,
    "numCapVertices":0,
    "pathArr":[
        0,0,0,
        500,500,0
        ,0,500,0
    ],
    "mainColor":"0xFF0011",
    "emissiveColor":null
}